version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: todo-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=todo-app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  hasura:
    image: hasura/graphql-engine:v2.38.0
    container_name: todo-hasura
    ports:
      - "8080:8080"
    environment:
      - HASURA_GRAPHQL_DATABASE_URL=postgres://postgres:postgrespassword@postgres:5432/todo-app
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
      - HASURA_GRAPHQL_DEV_MODE=true
      - HASURA_GRAPHQL_ENABLED_LOG_TYPES=startup, http-log, webhook-log, websocket-log, query-log
      - HASURA_GRAPHQL_ADMIN_SECRET=myadminsecretkey
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: todo-backend
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgres://postgres:postgrespassword@postgres:5432/todo-app
      - HASURA_ENDPOINT=http://hasura:8080
      - HASURA_ADMIN_SECRET=myadminsecretkey
    depends_on:
      postgres:
        condition: service_healthy
      hasura:
        condition: service_healthy
    command: sh -c "npm run init-db && sleep 5 && npm run init-hasura && npm run start:prod"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: todo-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
      - NEXT_PUBLIC_HASURA_URL=http://hasura:8080/v1/graphql
      - NEXT_PUBLIC_HASURA_ADMIN_SECRET=myadminsecretkey
    depends_on:
      - backend
      - hasura

volumes:
  postgres_data:
    driver: local
